### ISSUE TITLE
org.jose4j.lang.InvalidKeyException while pushing notification.

### ISSUE THREAD

**Issue by TechBall86** [web-push-libs/webpush-java#50]
I'm getting a org.jose4j.lang.InvalidKeyException, when i'm trying to push a notification:

**Exception:**
```
2018-02-20 18:20:46,787|000-exec-2|ERROR|boration.review.ReviewOverview|The given key (algorithm=ECDH) is not valid (not a private key or is the wrong type of key) for SHA256withECDSA / ES256 java.lang.ClassCastException: org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey cannot be cast to java.security.interfaces.ECPrivateKey
org.jose4j.lang.InvalidKeyException: The given key (algorithm=ECDH) is not valid (not a private key or is the wrong type of key) for SHA256withECDSA / ES256 java.lang.ClassCastException: org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey cannot be cast to java.security.interfaces.ECPrivateKey
	at org.jose4j.jws.BaseSignatureAlgorithm.validateSigningKey(BaseSignatureAlgorithm.java:160)
	at org.jose4j.jws.JsonWebSignature.sign(JsonWebSignature.java:98)
	at org.jose4j.jws.JsonWebSignature.getCompactSerialization(JsonWebSignature.java:73)
	at nl.martijndwars.webpush.PushService.preparePost(PushService.java:198)
	at nl.martijndwars.webpush.PushService.sendAsync(PushService.java:131)
	at nl.martijndwars.webpush.PushService.send(PushService.java:118)
	at de.aeneis.web.collaboration.review.ReviewOverview$2.onEvent(ReviewOverview.java:154)
	at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:3163)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3133)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3075)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:138)
	at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1853)
	at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1625)
	at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1328)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.process(DHtmlUpdateServlet.java:606)
	at de.aeneis.bpmportal.zk.UpdateServlet.process(UpdateServlet.java:53)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:482)
	at de.aeneis.bpmportal.zk.UpdateServlet.doGet(UpdateServlet.java:43)
	at org.zkoss.zk.au.http.DHtmlUpdateServlet.doPost(DHtmlUpdateServlet.java:490)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.swagger.api.ApiOriginFilter.doFilter(ApiOriginFilter.java:16)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**My Code:**
```java
Security.addProvider(new BouncyCastleProvider());

PushService pushService = new PushService()
  .setPublicKey(PUBLIC_KEY)
  .setPrivateKey(PRIVATE_KEY)
  .setSubject("mailto:admin@domain.com");

nl.martijndwars.webpush.Subscription subscription = new nl.martijndwars.webpush.Subscription();

Subscription.Keys keys = subscription.new Keys(
  "BFxzKvlzk9tarZ5f2M7DUwBJEWxeJ4IQ_yety8cE8TgfWwSLPKeUROxxlnPUNN5SCoAJd3KE3nBBcQ9JCrMPsm0=",
  "JoLTqdBPvO-FdQT01A6w-Q=="
);

nl.martijndwars.webpush.Subscription subscription2 = new nl.martijndwars.webpush.Subscription(
  "https://fcm.googleapis.com/fcm/send/d7NgqbmcoKo:APA91bG3J9OCjcjdGYGVWhtGVjB2nFUcKQTuePjUYMxQ2TH8HEUXLH7EwXcFQvIZ4pAvPT3_y7aIu6kYTJdcoo_qy4ukG3C3fLOK2-YZwYS5eRtpvo3gbuPM5ZxD6YLxmr0WLP0rOXlk",
  keys
);

Notification notification = new Notification(subscription2, "Hello");

pushService.send(notification);
```

The work on the client side is done and it seems to be ok.
The keys are created with GenerateKeyCommand.java
I use localhost in my browser for tests.

What i am doing wrong?

Thx

**Comment by martijndwars** [comment]
I don't really understand this error:

```
java.lang.ClassCastException: org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey cannot be cast to java.security.interfaces.ECPrivateKey
```

`org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey ` is a subclass of `java.security.interfaces.ECPrivateKey`, so the cast is an upcast. Since upcasting is always safe, you should never get a ClassCastException.

Could it be that you're using a different version of BouncyCastle? I see that in version 1.48, [BCECPrivateKey](http://www.atetric.com/atetric/javadoc/org.bouncycastle/bcprov-jdk14/1.48/org/bouncycastle/jcajce/provider/asymmetric/ec/BCECPrivateKey.html) did not implement  `java.security.implementations.ECPrivateKey` (not to be confused with `org.bouncycastle.jce.interfaces.ECPrivateKey`, which it does implement). That would explain why the cast is failing. I've used BouncyCastle v1.54 with this library without any problems, perhaps you could try this? Let me know if this works, then I'll make a note in the README to instruct future users to use a recent version of BouncyCastle.

**Comment by martijndwars** [comment]
I took another look. For every BouncyCastle release there is an artifact targeting JDK 1.4 and an artifact targeting JDK 1.5 - JDK 1.8.

- In the version that targets JDK 1.4, the BCECPrivateKey class *does not* implement java.security.implementations.ECPrivateKey.
- In the version that targets JDK 1.5 - JDK 1.8, the BCECPrivateKey class *does* implement java.security.implementations.ECPrivateKey.

This makes sense, since java.security.implementations.ECPrivateKey was introduced in JDK 1.5. Please make sure you're using the the BouncyCastle provider targeting JDK 1.5 - JDK 1.8 (commonly referred to as `bcprov-jdk15on` and available from Maven Central or the [BouncyCastle website](https://www.bouncycastle.org/latest_releases.html)).

**Comment by TechBall86** [comment]
That solved my problem !

THX !
